### ISSUE TITLE
Enabling Override Fog Color causes the game to crash when loading a world

### ISSUE THREAD

**Issue by CapoFantasma97** [fabbe50/FogOverrides#16]
Minecraft version: 1.20.1
Mod Loader: NeoForge 47.1.106
Mod Version: 1.3

When enabling Override Fog Color in a world, it crashes the game.

Enabling Override Fog Color and then loading the world also causes a game crash.

https://gist.github.com/CapoFantasma97/84f9708c2cf8e87151a55542690552f2

**Comment by fabbe50** [comment]
You need the Architectury API installed for this version of the mod.
Must have missed adding that as a requirement in the mod, that's my bad.
